### ISSUE TITLE
Store sensitive credentials in environment & import

### ISSUE THREAD

**Issue by nitishdhar** [jplahn/rental_app#2]
Reset the current DB credentials and start using an env setup to use credentials from local env or config & gitignore that config file that stores these credentials

Then share credentials outside of the code repo

More - https://www.reddit.com/r/learnpython/comments/264ffw/what_is_the_pythonic_way_of_storing_credentials/

**Comment by jplahn** [comment]
Yeah this was something I wanted to take care of when I got the DB ready. I'll set this up this weekend.

**Comment by jplahn** [comment]
Commit got messed up, but done here https://github.com/jplahn/rental_app/commit/57bb361e8c884f994f0551f3672e6a20a4131fa8. 

Closing.
