### ISSUE TITLE
Hosted demo

### ISSUE THREAD

**Issue by nitishdhar** [jplahn/rental_app#3]
would be great to have a hosted demo running somewhere on heroku or something

**Comment by jplahn** [comment]
Working on this.

**Comment by jplahn** [comment]
Let me know if you guys can hit this: https://mighty-dusk-21031.herokuapp.com/. 

We'll need to setup the DB and such still.

**Comment by nitishdhar** [comment]
Can reach it, submit fails

**Comment by jplahn** [comment]
Yeah that's the behavior right now (I assume you entered a city other than Seattle and got a 404?).

**Comment by nitishdhar** [comment]
I entered "seattle", lowercase. So yeah mark an issue to do case ignored comparison

**Comment by jplahn** [comment]
Resolving in favor of https://github.com/jplahn/rental_app/issues/4.
